component:
  rate_limiter:
    enabled: true
      whitelist:
      ip_open:
      interface_open:
    path:

spring:
  application:
    name: component-rate-limiter
  redis:
    database: 0
    host: 127.0.0.1
    password:
    pool:
      max-active: 8
      max-idle: 8
      max-wait: -1
      min-idle: 0
    port: 6379
    timeout: 5000

